#!/bin/bash

#set -x

log2=sysinfo-$HOSTNAME-$(date +%y%m%d%H%M%S)

echo -e "$HOSTNAME\n" > $log2

dmi=/sys/class/dmi/id
if [ -e $dmi ]
then
    cat $dmi/bios_vendor >> $log2
    cat $dmi/bios_version >> $log2
    cat $dmi/bios_date >> $log2
    echo -n -e "\n" >> $log2
    cat $dmi/board_vendor >> $log2
    cat $dmi/board_name >> $log2
fi

echo -n -e "\n" >> $log2
uname -r >> $log2

echo >> $log2
free >> $log2

echo >> $log2
lscpu >> $log2
echo -e "\nPCI\n" >> $log2
lspci >> $log2
echo -e "\nUSB\n" >> $log2
lsusb >> $log2

echo -e "\nDrives\n" >> $log2
#set -x
#echo >> $log2
# ATA Link 5 <unknown>
for (( i=1 ; i<11 ; i++ ))
do
    link=/sys/class/ata_link/link$i
    if [ ! -e $link ]
    then
	break
    fi
    s=$(cat $link/sata_spd)
    #[ "$s" != "<unknown>" ] && echo "ATA Link" $i $s >> $log2
    #[ "$s" != "<unknown>" ] && link[$i]="ATA Link $i $s"
    [ "$s" != "<unknown>" ] && link[$i]="$s"
done
#exit
scsi=/proc/scsi/scsi
#cat /proc/scsi/scsi >> $log2
#set -x
s=scsi0
while read line
do
    #echo $line
    w1=$(echo $line|cut -d \  -f 1)
    case $w1 in
	"Host:")
	    s=$(echo $line|cut -d \  -f 2)
	    ;;
	"Vendor:")
	    #drive=$(echo $line|cut -d \  -f 2-)
	    drive=${line:8}
	    ;;
	"Type:")
	    t=$(echo $line|cut -d \  -f 2)
	    i=$((${s:4}+1))
	    #echo "$s $t $drive ${link[$i]}" >> $log2
	    printf "%s %-13s %s %s\n" "$s" "$t" "$drive" "${link[$i]}" >> $log2
	    ;;
    esac
done < $scsi
echo >> $log2
nvm="/sys/block/*"
for r in $nvm
do
    #echo $r
    [ ! -e "$r/device" ] && continue
    name=$(basename $r)
    model=$(cat $r/device/model)
    [ -e $r/device/firmware_rev ] && rev=$(cat $r/device/firmware_rev)
    [ -e $r/device/rev ] && rev=$(cat $r/device/rev)
    [ -e $r/device/transport ] && transport=$(cat $r/device/transport)
    size=$(cat $r/size)
    size=$(($size/2/1000000))
    #echo $name $model $firmware_rev $size"G" $transport >> $log2
    printf "%s Model: %-13s Rev: %s %s %s\n" $name "$model" $rev $size"G" $transport >> $log2
done
#exit
echo >> $log2
#if [ -e /proc/scsi/sg ]
#then
#    cat /proc/scsi/sg/device_strs >> $log2
#fi
#set -x
if [ -e /sys/class/drm/card0/device/uevent ]
then
    dr=$(grep "DRIVER=" /sys/class/drm/card0/device/uevent)
    echo -e "\n$dr" >> $log2
    [ -e /sys/class/drm/card0/device/current_link_speed ] && \
	cat /sys/class/drm/card0/device/current_link_speed >> $log2
    if [ -e /sys/class/drm/card0/device/current_link_width ]
    then
	echo -n "Width " >> $log2
	cat /sys/class/drm/card0/device/current_link_width >> $log2
    fi
fi
#exit

if [ -e /proc/driver/nvidia ]
then
    echo -e "\nNvidia\n" >> $log2
    pci_adr=$(ls /proc/driver/nvidia/gpus)
    cat /proc/driver/nvidia/gpus/$pci_adr/information >> $log2
    cat /proc/driver/nvidia/version >> $log2
fi
# DVB
echo -e "\nDVB\n" >> $log2
#set -x
for (( i=0 ; i<10 ; i++ ))
do
    dvb=/sys/class/dvb/dvb$i.frontend0/device
    ca=/sys/class/dvb/dvb$i.ca0/device
    #if [ ! -e $dvb -a -e $ca ]
    #then
	#break
    #fi
    device=
    [ -e $ca ] && device=$ca
    [ -e $dvb ] && device=$dvb
    [ "$device" == "" ] && break
    d=$(grep "DRIVER=" $device/uevent)
    d=$(echo $d|cut -d '=' -f 2)
    if [ "$d" == "usb" ]
    then
	p=$(grep "PRODUCT=" $device/uevent)
	p=$(echo $p|cut -d '=' -f 2)
	d="$d $p"
    fi
    if [ -e $device/manufacturer ]
    then
	d="$d "$(cat $device/manufacturer)
    fi
    if [ -e $device/product ]
    then
	d="$d "$(cat $device/product)
    fi
    echo $i $d >> $log2
    #exit
done

echo -e "\nInterrupts\n" >> $log2
cat /proc/interrupts >> $log2
less $log2
